{{- $allSecrets := include "helpers.getAllSecrets" . | fromYaml }}
{{- if $allSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-nginx-chart.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "my-nginx-chart.labels" . | nindent 4 }}
  annotations:
    merge-strategy: "intelligent-helper-template"
    merged-levels: "base,env1,env2,env3,override,custom"
type: Opaque
data:
{{- range $key, $value := $allSecrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
