apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "todolist.fullname" . }}-cleanup
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
    app.kubernetes.io/component: cronjob
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  suspend: {{ .Values.cronjob.suspend }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "todolist.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: cronjob
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name }}-cleanup
              image: "{{ default .Values.image.repository .Values.cronjob.image.repository }}:{{ default .Values.image.tag .Values.cronjob.image.tag }}"
              imagePullPolicy: {{ default .Values.image.pullPolicy .Values.cronjob.image.pullPolicy }}
              command: {{ toYaml .Values.cronjob.command | nindent 16 }}
              resources:
                {{- toYaml .Values.cronjob.resources | nindent 16 }}
              {{- if .Values.persistence.enabled }}
              volumeMounts:
                - name: data
                  mountPath: /app/data
              {{- end }}
          {{- if .Values.persistence.enabled }}
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: {{ include "todolist.fullname" . }}
          {{- end }}
{{- if not .Values.cronjob.enabled }}
{{ end }}
