apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx
    release: {{ .Release.Name }}
{{- if .Values.configmap.data }}
data:
{{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- if .Values.configmap.binaryData }}
binaryData:
{{- range $key, $value := .Values.configmap.binaryData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
