{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.name}}
spec:
  {{- if .Values.route.host }}
  host: {{.Values.route.host}}
  {{- end }}
  to:
    kind: Service
    name: {{.Values.name}}
    weight: 100
  port:
    targetPort: 80
  wildcardPolicy: None
{{- end }}
