replicaCount: 1
namespace: shubh
image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 96
  test2: shubh1
  ports:
    - port: 96
      targetPort: 9000
      name: api
    - port: 3000
      targetPort: 3000
      name: metrics-shubh
