NAME: nginx
REPLICAS: "1"
IMAGE: nginx
IMAGE_TAG: latest
IMAGE_PULL_POLICY: IfNotPresent
SERVICE_TYPE: ClusterIP
SERVICE_PORT: "80"
RESOURCE_LIMIT_CPU: 100m
RESOURCE_LIMIT_MEMORY: 128Mi
RESOURCE_REQUEST_CPU: 50m
RESOURCE_REQUEST_MEMORY: 64Mi
