{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-nginx-chart.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
