apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-complex.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nginx-complex.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nginx-complex.selectorLabels" . | nindent 4 }}
  ports:
  - name: {{ .Values.service.ports.http.name }}
    port: {{ .Values.service.ports.http.port }}
    targetPort: {{ .Values.service.ports.http.targetPort }}
  - name: {{ .Values.service.ports.metrics.name }}
    port: {{ .Values.service.ports.metrics.port }}
    targetPort: {{ .Values.service.ports.metrics.targetPort }}
  type: {{ .Values.service.type }}
