apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.releaseName }}-nginx
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx
    environment: {{ .Values.environment }}
    release: {{ .Values.releaseName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
      release: {{ .Values.releaseName }}
  template:
    metadata:
      labels:
        app: nginx
        release: {{ .Values.releaseName }}
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5

