apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.releaseName }}-nginx-service
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx
    release: {{ .Values.releaseName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: nginx
    release: {{ .Values.releaseName }}

