# Values with Harness expression (only replicaCount)
replicaCount: <+pipeline.variables.replicas>
# replicaCount: 3

namespace: default

image:
  repository: nginx
  tag: 1.21.6
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

environment: production
releaseName: my-app

# Potential lint issue: Invalid value that might cause issues
invalidPort: "not-a-number"

# Simple numeric values
minReplicas: 2
maxReplicas: 10

